version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/md-test-project
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
  AfterInstall:
    - location: scripts/AfterInstall.sh